#ifndef MAP__
#define MAP__

#define MAN_UP				(0)
#define MAN_DOWN			(1)
#define MAN_LEFT			(2)
#define MAN_RIGHT			(3)
#define BOX					(4)
#define MAN_UP_TARGET		(5)
#define MAN_DOWN_TARGET		(6)
#define MAN_LEFT_TARGET		(7)
#define MAN_RIGHT_TARGET	(8)
#define BOX_TARGET			(9)
#define WALL				(10)
#define TARGET				(11)
#define ROAD				(12)
#define TARGET2BASE			(-5)
#define BASE2TARGET			(+5)
#define IS_TARGET(x)		(x >= 5 && x <= 9)

#define NONE				(-1)

int map_stage_0[10][10] =
{
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE,
	NONE, NONE, NONE, WALL, WALL, WALL, WALL, NONE, NONE, NONE,
	NONE, NONE, NONE, WALL, ROAD, ROAD, WALL, WALL, WALL, NONE,
	NONE, WALL, WALL, WALL, BOX, ROAD, ROAD, ROAD, WALL, NONE,
	NONE, WALL, ROAD, ROAD, TARGET, TARGET, ROAD, ROAD, WALL, NONE,
	NONE, WALL, ROAD, BOX, ROAD, TARGET, ROAD, ROAD, WALL, NONE,
	NONE, WALL, WALL, WALL, ROAD, BOX, WALL, WALL, WALL, NONE,
	NONE, NONE, NONE, WALL, ROAD, MAN_UP, WALL, NONE, NONE, NONE,
	NONE, NONE, NONE, WALL, WALL, WALL, WALL, NONE, NONE, NONE,
	NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE
};

#endif // !MAP__

